### ISSUE TITLE
[Code] Colors and Animals

### ISSUE THREAD

**Issue by kellycesario** [kellycesario/javascript-oceandex#59]
Establish a relationship between colors and animals @xossiane

**Comment by xossiane** [comment]
Distincts by PHYLUM

Cnidaria #B64760: Anemone (id 0), Sea Fan (id 6), Jellyfish (11)

Chordata #B34884: Angel Fish (id 1), Cod (id 2), Dolphin (id 3), Blue Whale (id 4), Clown Fish (id 5), Moray Eel (id 9), Green Sea Turtle (id 10), Humpback Whale (id 12), Killer Whale (id 13), Narwhal (id 14), Olive Turtle (id 17), Sting Ray (id 19), Sea Horse (id 20), White Shark (id 24), Sword Fish (id 28), Tuna Fish (id 29)

Arthropoda #737185: Crab (id 7), Shrimp (id 25)

Mollusca #687696 : Dumbo Octopus (id 8), Nautilus (id 15), Octopus (id 16), Oyster (id 18), Squid (id 26) 

Echinodermata #567A79: Sea Urchin (id 21), Star Fish (id 27)

Chlorophyta: Seaweed (id 23)
